---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['**']
    paths:
      - '**.js'
  pull_request:
    branches: [master, release-*]
    paths:
      - '**.js'
  workflow_dispatch:

jobs:
  eslinter:
    name: 'JavaScript Linter'
    uses: simplesamlphp/simplesamlphp-test-framework/.github/workflows/reusable_eslinter.yml@2f8980a72346dd91d9d6b2adc89e589dc1736238
