---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['**']
    paths:
      - '**.css'
      - '**.sass'
      - '**.scss'
  pull_request:
    branches: [master, release-*]
    paths:
      - '**.css'
      - '**.sass'
      - '**.scss'
  workflow_dispatch:

jobs:
  stylelinter:
    name: 'Stylesheet Linter'
    uses: simplesamlphp/simplesamlphp-test-framework/.github/workflows/reusable_stylelinter.yml@2f8980a72346dd91d9d6b2adc89e589dc1736238
